### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by ghost** [kjetilmjos/node-nmap-viewer#17]
Hello again!
I had fun using this program, really enjoy this. This program can be helpful in some ways. But now I have 2 questions. First Can I contact with You via email? And next, I need to have a program like this but, to scan topology(For example. Scanning connections between me and google). I know How nmap is working via console, but node.js im retarded It's not my thing. The best for me if i had a contact to You. Best regards

**Comment by koleksz** [comment]
Hi! 
First I will explain my problem. So I tried change program to topology study. I know It's not issue and better to contact with you via mail, maybe if you read this, we can contact. There is a problem with ipnett and iprange I don't know how to delete this or avoid? And after I change     
for (k in result.nmaprun.host[0].trace[0].hop[0]) {
          s = (result.nmaprun.host[0].trace[0].hop[k].$.ipaddr)
There is an error : TypeError: Cannot read property '$' of undefined.
Everyday I'm learning about JS, node. I really need this tu redesign this for exam

**Comment by kjetilmjos** [comment]
Hello, sure you can. Made my email viewable on my profile, so feel free to email me.
